version: '2.1'

services:
  db:
    container_name: db_dev
    hostname: db_dev
    image: mariadb
    networks:
      dev-network:
        ipv4_address: 192.168.202.4
    env_file:
      - mariadb.env
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck: 
      test: 'service mysql restart'
      timeout: 30s
      interval: 30s
      retries: 3 

  django_dev:
    build: ./django_dev
    container_name: django_dev
    hostname: django_dev
    image: django_dev
    networks:
      dev-network:
        ipv4_address: 192.168.202.3
    depends_on:
      db:
        condition: 'healthy'

  nginx_dev:
    build: ./nginx_dev
    container_name: nginx_dev
    hostname: nginx_dev
    image: nginx_dev
    networks:
      dev-network:
        ipv4_address: 192.168.202.2
    depends_on:
      - django_dev

networks:
  bay:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/24

volumes:
  db-data:
