version: '2.1'

services:
  backend:
    build: ./backmariadb
    container_name: backend
    image: backend_dev
    ports:
      - "3306:3306"
    networks:
      app-net:
        ipv4_address: 192.168.100.2
    volumes:
      - backend-data:/var/lib/mysql
    healthcheck: 
      test: '/usr/bin/mysql -D appdb -u maria --password=password -e "show databases;"'
      timeout: 10s
      interval: 30s
      retries: 3 

  midend:
    build: ./middjango
    container_name: midend
    image: midend_dev 
    ports:
      - "8000:8000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      app-net:
        ipv4_address: 192.168.100.3
    extra_hosts: 
      - "backend:192.168.100.2"

  frontend:
    build: ./frontnginx
    container_name: frontend
    image: frontend_dev
    ports:
      - "80:80"
    depends_on:
      - midend
    networks:
      app-net:
        ipv4_address: 192.168.100.4
    extra_hosts:
      - "midend:192.168.100.3"

volumes:
  backend-data:

networks:
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

